version: '2'
services:
  db:
    image: mysql:5.7.11
    environment:
      - MYSQL_ROOT_PASSWORD=foo
  app:
    image: php-mysql
    container_name: enidservice
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=foo
      - MYSQL_USER=root