version: '3'
services:
  web:
      build: .
      ports:
          - "80:80"
      volumes:
           - ./:/var/www/html
           - ./site.conf:/etc/nginx/conf.d/site.conf
      extra_hosts:
          - "backend.de.com:127.0.0.1"      
      environment:
        PHP_XDEBUG_ENABLED: 1
        #XDEBUG_CONFIG: remote_host=192.168.1.4
        #PHP_IDE_CONFIG: "serverName=developer"
        WEBSERVER_USER: www-data                          
      links:
        - php
      container_name: backend_developer_web

  php:
      image: php:7-fpm
      links:
        - db

  db:

    image: mariadb:10.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: enidserv_web
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    volumes:
      - ../mysql/config:/etc/mysql/conf.d
      - ../mysql/databasedata:/var/lib/mysql
    ports:
        - 3306:3306
    container_name: backend_developer_db