# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: php:5.6-apache
    working_directory: /var/www/html
    steps:
      - checkout
      - run:
          name: Update packages ...
          command: apt-get update
      - run:
          name: Install packages 1/2 ...
          command: apt-get install -y libmcrypt-dev python-pip libicu-dev libxml2-dev
      - run:
          name: Install packages 2/2 ...
          command: apt-get install -y libxslt1-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev git vim openssh-server ocaml expect mysql-client
      - run:
          name: Active docker configure gd ...
          command: docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run:
          name: Active docker configure hash ...
          command: docker-php-ext-configure hash --with-mhash
      - run:
          name: Install docker php extensions ...
          command: docker-php-ext-install bcmath mcrypt intl json gd pdo_mysql mysql mysqli soap xsl zip
      - run:
          name: Install Composer ...
          command: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install dependences ...
          command: composer install
      - run:
          name: Check lint syntaxis ...
          command: ./vendor/bin/parallel-lint --exclude vendor .
      - run:
          name: Check php unit test ...
          command: ./vendor/bin/phpunit

  deploy_devops:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Update Packages
          command: sudo apt-get update
      - run:
          name: Install Rsync
          command: sudo apt-get install rsync -y
      - run: pwd
      - run: ls -al
      - run:
          name: Deploy DevOps SSH
          command: rsync -rae ssh --delete --verbose /home/circleci/project/* jenkins@devops.benandfrank.com:/www/devops.benandfrank.com

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_devops:
          requires:
            - build
          filters:
            branches:
              only: staging