version: '2'
services:
  web:
      image: test_php_apache
      expose:
         - "9000"
      ports:
          - "80:80"
          - "443:443"
          - "8116:22"
      volumes:
          - ./:/var/www/html
          - ~/.ssh:/home/enid/.ssh

      tty: true

      links:
          - mysql
      container_name: enidservice-web

  mysql:

      image: mysql:5.7
      volumes:
      - ../mysql/config:/etc/mysql/conf.d
      - ../mysql/databasedata:/var/lib/mysql
      ports:
        - 3307:3306
      environment:
          - MYSQL_ROOT_PASSWORD=mysql
          - MYSQL_DATABASE=enidserv_web
      container_name: enidservice-db